### ISSUE TITLE
DetachedContext fails to get service IDetachedContextServices

### ISSUE THREAD

**Issue by henrikstromberg** [leonardoporro/EntityFrameworkCore.Detached#2]
I have added   services.AddTransient(typeof(IDetachedContext<>), typeof(DetachedContext<>));
in my Setup class but when the  DetachedContext is created the code in DetachedContext fails to get service.  _detachedServices = _serviceProvider.GetService<IDetachedContextServices>();

What am i missing ?

**Comment by leonardoporro** [comment]
UseDetached() missing when configuring the scope? Or AddDetachedEntityFramework() to your external service provider?
